openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:50000'
paths:
    /JeMPI/count-golden-records:
      get:
        summary: Get the number of golden records
        responses:
          "200":
            description: "OK"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    count:
                      type: integer
                      example: 444
    /JeMPI/count-interactions:
      get:
        summary: Get the number of interactions
        responses:
          "200":
            description: "OK"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    count:
                      type: integer
                      example: 444
    /JeMPI/count-records:
      get:
        summary: Get the number of records
        responses:
          "200":
            description: "OK"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    goldenRecords:
                      type: integer
                      example: 444
                    interactions:
                      type: integer
                      example: 607
    /JeMPI/gids-all:
      get:
        summary: Get all golden identifiers
        responses:
          "200":
            description: "OK"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    gidList:
                      type: array
                      items: {string}
                      example:
                        ["0x5", "0x8", "0xb"]
    /JeMPI/gids-paged:
      parameters:
        - schema:
            type: integer
            example: 0
          name: offset
          in: header
          required: true
        - schema:
            type: integer
            example: 100
          name: length
          in: header
          required: true
      get:
        summary: Get paginated golden identifiers
        responses:
          "200":
            description: "OK"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    gidList:
                      type: array
                      items: {string}
                      example:
                        ["0x5", "0x8", "0xb"]
    /JeMPI/interaction/{iid}:
      parameters:
        - schema:
            type: string
            example: "0x4"
          name: iid
          in: path
          required: true
      get:
        summary: Fetches interaction
        responses:
          "200":
            description: "OK"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/interaction"
    /JeMPI/expanded-golden-record/{gid}:
      parameters:
        - schema:
            type: string
            example: "0x5"
          name: gid
          in: path
          required: true
      get:
        summary: Fetches expanded golden record
        responses:
          "200":
            description: "OK"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/golden-record"
    /JeMPI/Unlink:
      parameters:
        - schema:
            type: string
            example: "0x5"
          name: goldenId
          in: header
          required: true
      patch:
        responses:
          "200":
            description: "OK"


components:
  schemas:
    demographicData:
      type: object
      properties:
        auxId:
          type: string
          example: "rec-00000681-bbb-1"
        givenName:
          type: string
          example: "Leuleselassie"
        familyName:
          type: string
          example: ""
        gender:
          type: string
          example: "male"
        dob:
          type: string
          example: "20140421"
        city:
          type: string
          example: "Mwingi"
        phoneNumber:
          type: string
          example: "034-263-8586"
        nationalId:
          type: string
          example: "200006222481549"
    sourceId:
      type: object
      properties:
        facility:
          type: string
          example: "LABORATORY"
        patient:
          type: string
          example: "200006222481549"
        uid:
          type: string
          example: "0x3"
    interaction:
      type: object
      properties:
        demographicData:
          $ref: "#/components/schemas/demographicData"
        sourceId:
          $ref: "#/components/schemas/sourceId"
        iid:
          type: string
          example: "0x4"
    golden-record:
      type: object
      properties:
        demographicData:
          $ref: "#/components/schemas/demographicData"
        sourceId:
          $ref: "#/components/schemas/sourceId"
        uid:
          type: string
          example: "0x5"
